# This file is used for development only.
# It spins up a local DB and other cloud
# utilized systems that can be ran locally.

version: "3"
services:
  msoa-local-db:
    image: postgres:9.6
    networks:
      - msoa-local
    restart: always
    environment:
      POSTGRES_DB: msoadev
      POSTGRES_PASSWORD: msoa_s3cr3t
      POSTGRES_USER: msoadev
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - db-persistence:/var/lib/postgresql

networks:
  msoa-local:
    driver: bridge

volumes:
  db-persistence:

